name: e14env
channels:
  - conda-forge
dependencies:
  - gdown
  - ipykernel
  - matplotlib
  - numpy
  - opencv
  - pandas
  - pillow
  - python=3.10
  - scikit-learn
  - seaborn
  - timm
  - torchvision
  - transformers
prefix: /home/renee.zac/miniforge3/envs/e14env
