name: e14env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - ipykernel
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - torchvision
  - transformers
  - timm
  - pillow
  - opencv
  - gdown
  - seaborn
prefix: /Users/renee/miniforge3/envs/e14env
